### ISSUE TITLE
Mouse locked

### ISSUE THREAD

**Issue by crackfed** [pedromagician/CMD_MessageBox#1]
While the app window is open, the mouse cannot click on anything else. Other weird behavior locking mouse.

**Comment by pedromagician** [comment]
That's strange. I can't reproduce this behavior yet.

I've fixed the parameter processing and the window is the topmost.

**Comment by crackfed** [comment]
I figured it out.  I was using call start /B /MIN MessageBoxEx.exe and the /MIN option was causing it to lock.
