### ISSUE TITLE
Can't click Windows button

### ISSUE THREAD

**Issue by crackfed** [pedromagician/CMD_MessageBox#2]
This is weird and maybe related to that last issue.  When the messagebox app is open I can' t click the Windows menu icon in the lower left.  See if you can reproduce.

**Comment by pedromagician** [comment]
I can't reproduce it :(
It is CMD_MessageBox or CMD_MessageBoxEx? Which version of Windows? What are the parameters in the command line (I'll try to test it)?

**Comment by crackfed** [comment]
Sorry, this may be another case of user error. I'm not sure I can reproduce it either.

Is there a switch to force the window to stay on top?

**Comment by crackfed** [comment]
So you can see what I'm doing.
[VM.ZIP](https://github.com/pedromagician/CMD_MessageBox/files/8815098/VM.ZIP)

**Comment by crackfed** [comment]
oops missing one file

[VM.ZIP](https://github.com/pedromagician/CMD_MessageBox/files/8818266/VM.ZIP)

**Comment by pedromagician** [comment]
Theory:
The switch in MicroCMD /m minimizes the window in which the script executes, and also the message window.

Try a version of DEVELOP that has the window set as TOP, give it a try. If it helps, I'll add this option to the parameters.

[MessageBoxEx-DEV.zip](https://github.com/pedromagician/CMD_MessageBox/files/8818463/MessageBoxEx-DEV.zip)

**Comment by crackfed** [comment]
I don't have Visual Studio installed so I don't have all the dll files it needs to run.

**Comment by pedromagician** [comment]
ok, there is a new version that has the -topmost parameter

https://github.com/pedromagician/CMD_MessageBoxEx/blob/main/Bin/MessageBoxEx.exe

**Comment by crackfed** [comment]
Here's the issue I'm having. There are 3 things that need to happen when MBEx runs:
1. ONLY the MBEx app window should open. The bat file CMD window should stay minimized.
	This works OK when I use 'start /B ...'
2. The taskbar buttons should remain UNLOCKED and clickable.
	This only works if not using /B. But then it opens both windows.
3. The bat program should PROCEED after MBEx starts without clicking the button to close it.
	Only 'start ...' or 'start /B ..' allows this

Is there a solution?

**Comment by crackfed** [comment]
[inputbox.zip](https://github.com/pedromagician/CMD_MessageBox/files/8828522/inputbox.zip)

This is an example of an app that works well when started with 'start /B'

**Comment by crackfed** [comment]
[WinMsg.ZIP](https://github.com/pedromagician/CMD_MessageBox/files/8830062/WinMsg.ZIP)
Another example of an app that behaves properly with start /B.

What sets your app apart Pedro is that it allows a bmp to be in the mbox. I hope you can work out this kink because I see a lot of potential for it.

**Comment by pedromagician** [comment]
There's a new version 0.6, I've added the ability to add an app icon (-iconapp) and hopefully the console blocking is removed.

Please try it.
https://github.com/pedromagician/CMD_MessageBoxEx

**Comment by crackfed** [comment]
Oh yes!  It's so much better. Behaves very well from what I've seen so far. I'll put it through some harder testing in the next few days. Thank you.  This looks like a winner.

One interesting thing I found is that you can hide the button under the pic and still click it.

**Comment by crackfed** [comment]
It's not returning errorlevels for the buttons OK, Yes, No, etc.  They are listed here https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox

Also, if the first line of text starts with a space it adds a double quote chr. at the beginning.

**Comment by pedromagician** [comment]
- I added a function to set %errorlevel%
- The default return value is the button order. The -wrc parameter enables the "window return code".
- The message may already begin with a space. (-m " message\nmessage")
