### ISSUE TITLE
1 step forward...

### ISSUE THREAD

**Issue by crackfed** [pedromagician/CMD_MessageBox#4]
2 steps back.
 I'm not happy. You've removed some of the most useful switches, including:
topmost, fontsize, font, icon, iconsize, width, lines
All of these, except maybe topmost, are important. Very important. Please reinstate them. 
btw, icon is listed in the help but it does not work. 
The return codes are fine but they don't need to echo when the app closes.
I see you fixed the lone double quote bug but I hope it wasn't by removing all those features. If it was, I'd trade the bug for the features.
Please bring back the lost switches.

**Comment by pedromagician** [comment]
I feel like a mistake has happened.
The switches are still there, but you have to distinguish between [MessageBox](https://github.com/pedromagician/CMD_MessageBox) and [MessageBoxEx](https://github.com/pedromagician/CMD_MessageBoxEx).

**Comment by pedromagician** [comment]
The "quiet" parameter has been added.
